[package]
name = "genetic"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
lazy_static = "1.4.0"
rand = "0.8.5"
textplots = "0.8.6"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
